# Generated by Django 6.0.4 on 2026-05-22 20:52

import django.core.validators
import django.db.models.deletion
import shop.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=180, verbose_name='Название')),
                ('price_per_square_meter', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за м²')),
                ('density', models.CharField(blank=True, max_length=80, verbose_name='Плотность')),
                ('roll_width_cm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина полотна, см')),
                ('property_type', models.CharField(blank=True, max_length=120, verbose_name='Тип свойства')),
                ('uv_resistance', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='УФ-стойкость')),
                ('durability', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Долговечность')),
                ('strength', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Прочность')),
                ('care', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Уход')),
                ('purpose', models.TextField(blank=True, verbose_name='Назначение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('draft', 'Черновик'), ('archived', 'Снят с публикации')], default='active', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Ткань',
                'verbose_name_plural': 'Ткани',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Fastener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=180, verbose_name='Название')),
                ('calculation_type', models.CharField(choices=[('fixed', 'Фиксированная цена'), ('per_item', 'За штуку'), ('per_meter', 'За метр')], default='fixed', max_length=20, verbose_name='Тип расчета')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Цена')),
                ('compatibility', models.CharField(blank=True, max_length=255, verbose_name='Совместимость')),
                ('image', models.ImageField(blank=True, upload_to=shop.models.upload_to, verbose_name='Изображение')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('draft', 'Черновик'), ('archived', 'Снят с публикации')], default='active', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Крепление',
                'verbose_name_plural': 'Крепления',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=180, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to=shop.models.upload_to, verbose_name='Изображение')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('draft', 'Черновик'), ('archived', 'Снят с публикации')], default='active', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Элемент галереи',
                'verbose_name_plural': 'Галерея',
                'ordering': ('position', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author_name', models.CharField(max_length=120, verbose_name='Автор')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('image', models.ImageField(blank=True, upload_to=shop.models.upload_to, verbose_name='Изображение')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('draft', 'Черновик'), ('archived', 'Снят с публикации')], default='active', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=180, verbose_name='Название')),
                ('slug', models.SlugField(max_length=190, unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, upload_to=shop.models.upload_to, verbose_name='Изображение')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('draft', 'Черновик'), ('archived', 'Снят с публикации')], default='active', max_length=20, verbose_name='Статус')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='shop.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('position', 'title'),
            },
        ),
        migrations.CreateModel(
            name='DrawingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('waiting_manager', 'Ожидает подтверждения менеджером'), ('waiting_payment', 'Ожидает оплаты'), ('in_production', 'В производстве'), ('in_delivery', 'Передан в доставку'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='waiting_manager', max_length=30, verbose_name='Статус')),
                ('customer_name', models.CharField(max_length=180, verbose_name='Имя / компания')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('manager_comment', models.TextField(blank=True, verbose_name='Комментарий менеджера')),
                ('return_terms_accepted', models.BooleanField(default=False, verbose_name='Условия возврата подтверждены')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drawing_orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ по чертежу',
                'verbose_name_plural': 'Заказы по чертежу',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DrawingOrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('file', models.FileField(upload_to=shop.models.upload_to, verbose_name='Файл')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Исходное имя файла')),
                ('drawing_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='shop.drawingorder', verbose_name='Заказ по чертежу')),
            ],
            options={
                'verbose_name': 'Файл заказа по чертежу',
                'verbose_name_plural': 'Файлы заказа по чертежу',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to=shop.models.upload_to, verbose_name='Изображение цвета')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('draft', 'Черновик'), ('archived', 'Снят с публикации')], default='active', max_length=20, verbose_name='Статус')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colors', to='shop.fabric', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
                'ordering': ('fabric__title', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=180, verbose_name='Название')),
                ('shape', models.CharField(choices=[('rectangular', 'Прямоугольная'), ('round', 'Круглая'), ('wedge', 'Клиновидная'), ('oval', 'Овальная'), ('l_shaped', 'Г-образная'), ('u_shaped', 'П-образная')], max_length=30, verbose_name='Форма чехла')),
                ('code', models.SlugField(max_length=120, unique=True, verbose_name='Код')),
                ('coefficient', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=8, verbose_name='Коэффициент K')),
                ('min_size_cm', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)], verbose_name='Минимальный размер, см')),
                ('max_size_cm', models.PositiveIntegerField(default=500, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)], verbose_name='Максимальный размер, см')),
                ('expression', models.TextField(blank=True, verbose_name='Формула / выражение')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Параметры')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('draft', 'Черновик'), ('archived', 'Снят с публикации')], default='active', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Формула',
                'verbose_name_plural': 'Формулы',
                'ordering': ('shape', 'title'),
                'indexes': [models.Index(fields=['shape', 'status'], name='shop_formul_shape_5b732f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('number', models.CharField(max_length=40, unique=True, verbose_name='Номер заказа')),
                ('status', models.CharField(choices=[('waiting_manager', 'Ожидает подтверждения менеджером'), ('waiting_payment', 'Ожидает оплаты'), ('in_production', 'В производстве'), ('in_delivery', 'Передан в доставку'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='waiting_manager', max_length=30, verbose_name='Статус заказа')),
                ('payment_status', models.CharField(choices=[('not_paid', 'Не оплачен'), ('waiting_payment', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('refunded', 'Возврат')], default='not_paid', max_length=30, verbose_name='Статус оплаты')),
                ('customer_type', models.CharField(choices=[('person', 'Физическое лицо'), ('entrepreneur', 'ИП'), ('company', 'Юридическое лицо')], default='person', max_length=30, verbose_name='Тип клиента')),
                ('customer_name', models.CharField(max_length=180, verbose_name='Имя / компания')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('delivery_method', models.CharField(blank=True, max_length=120, verbose_name='Способ доставки')),
                ('delivery_city', models.CharField(blank=True, max_length=120, verbose_name='Город доставки')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Адрес доставки')),
                ('track_number', models.CharField(blank=True, max_length=120, verbose_name='Трек-номер')),
                ('payment_method', models.CharField(blank=True, choices=[('card', 'Банковская карта'), ('sbp', 'СБП'), ('invoice', 'Расчетный счет'), ('cash', 'Наличные')], max_length=30, verbose_name='Способ оплаты')),
                ('items_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Товары')),
                ('delivery_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Доставка')),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Скидка')),
                ('vat_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='НДС')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Итого')),
                ('client_comment', models.TextField(blank=True, verbose_name='Комментарий клиента')),
                ('manager_comment', models.TextField(blank=True, verbose_name='Комментарий менеджера')),
                ('return_terms_accepted', models.BooleanField(default=False, verbose_name='Условия возврата подтверждены')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=220, verbose_name='Название')),
                ('sku', models.CharField(max_length=80, unique=True, verbose_name='Артикул')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('width_cm', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)], verbose_name='Ширина, см')),
                ('depth_cm', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)], verbose_name='Глубина, см')),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)], verbose_name='Высота, см')),
                ('main_image', models.ImageField(blank=True, upload_to=shop.models.upload_to, verbose_name='Главное изображение')),
                ('purpose', models.TextField(blank=True, verbose_name='Назначение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Остаток')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('draft', 'Черновик'), ('archived', 'Снят с публикации')], default='active', max_length=20, verbose_name='Статус')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category', verbose_name='Категория')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.color', verbose_name='Цвет')),
                ('fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.fabric', verbose_name='Ткань')),
                ('fastener', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.fastener', verbose_name='Крепление')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('item_type', models.CharField(choices=[('catalog', 'Товар из каталога'), ('constructor', 'Товар из конструктора')], default='catalog', max_length=30, verbose_name='Тип позиции')),
                ('title', models.CharField(max_length=220, verbose_name='Название')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='Артикул')),
                ('shape', models.CharField(blank=True, choices=[('rectangular', 'Прямоугольная'), ('round', 'Круглая'), ('wedge', 'Клиновидная'), ('oval', 'Овальная'), ('l_shaped', 'Г-образная'), ('u_shaped', 'П-образная')], max_length=30, verbose_name='Форма чехла')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Параметры позиции')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за единицу')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='shop.product', verbose_name='Товар из каталога')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(upload_to=shop.models.upload_to, verbose_name='Изображение')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товара',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['status', 'position'], name='shop_catego_status_e2a02c_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'position'], name='shop_catego_parent__9982b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='color',
            constraint=models.UniqueConstraint(fields=('fabric', 'title'), name='unique_color_per_fabric'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='shop_order_user_id_f8b1c9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='shop_order_status_65feda_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status'], name='shop_produc_categor_c9aecd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='shop_produc_sku_9aec58_idx'),
        ),
    ]
