# Generated by Django 6.0.4 on 2026-05-23 08:26

import django.db.models.deletion
import shop.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=180, verbose_name='Название')),
                ('code', models.SlugField(max_length=80, unique=True, verbose_name='Код')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Цена')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('draft', 'Черновик'), ('archived', 'Снят с публикации')], default='active', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Аксессуар',
                'verbose_name_plural': 'Аксессуары',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='ConstructorAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('file', models.FileField(upload_to=shop.models.upload_to, verbose_name='Файл конструктора')),
                ('original_name', models.CharField(max_length=255, verbose_name='Исходное имя файла')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='Тип файла')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Размер файла, байт')),
            ],
            options={
                'verbose_name': 'Временный файл конструктора',
                'verbose_name_plural': 'Временные файлы конструктора',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItemFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('file', models.FileField(upload_to=shop.models.upload_to, verbose_name='Файл')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Исходное имя файла')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='shop.orderitem', verbose_name='Позиция заказа')),
            ],
            options={
                'verbose_name': 'Файл позиции заказа',
                'verbose_name_plural': 'Файлы позиции заказа',
                'ordering': ('id',),
            },
        ),
    ]
