# Generated by Django 6.0.4 on 2026-05-24 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_accessory_constructorattachment_orderitemfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('middle_name', models.CharField(blank=True, max_length=120, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                ('customer_type', models.CharField(choices=[('person', 'Физическое лицо'), ('entrepreneur', 'ИП'), ('company', 'Юридическое лицо')], default='person', max_length=30, verbose_name='Тип клиента')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль клиента',
                'verbose_name_plural': 'Профили клиентов',
            },
        ),
    ]
