# Generated by Django 6.0.4 on 2026-05-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('purpose', models.CharField(choices=[('login', 'Вход'), ('register', 'Регистрация')], max_length=20, verbose_name='Назначение')),
                ('code_hash', models.CharField(max_length=255, verbose_name='Хэш кода')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные формы')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попытки')),
                ('max_attempts', models.PositiveSmallIntegerField(default=5, verbose_name='Максимум попыток')),
            ],
            options={
                'verbose_name': 'Код входа по email',
                'verbose_name_plural': 'Коды входа по email',
                'ordering': ('-created_at',),
                'indexes': [
                    models.Index(fields=['email', 'purpose', '-created_at'], name='shop_emaila_email_da3e20_idx'),
                    models.Index(fields=['expires_at', 'used_at'], name='shop_emaila_expires_81bd21_idx'),
                ],
            },
        ),
    ]
