# Generated by Django 6.0.4 on 2026-05-26 11:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_emailauthcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='minimum_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=12, verbose_name='Минимальная стоимость изделия'),
        ),
    ]
