# Generated by Django 6.0.4 on 2026-05-26 12:37

from django.db import migrations, models


def normalize_fastener_calculation_type(apps, schema_editor):
    Fastener = apps.get_model('shop', 'Fastener')
    Fastener.objects.exclude(calculation_type='fixed').update(calculation_type='fixed')


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_formula_minimum_price'),
    ]

    operations = [
        migrations.RunPython(normalize_fastener_calculation_type, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='fastener',
            name='calculation_type',
            field=models.CharField(choices=[('fixed', 'Цена за комплект')], default='fixed', max_length=20, verbose_name='Тип цены'),
        ),
    ]
