# Generated by Django 6.0.4 on 2026-05-26 13:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_fastener_calculation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='edging_price_cm',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Окантовочный шов, руб./см'),
        ),
        migrations.AddField(
            model_name='formula',
            name='seam_price_cm',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Стачной шов, руб./см'),
        ),
        migrations.AddField(
            model_name='formula',
            name='topstitch_price_cm',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Отстрочный шов, руб./см'),
        ),
    ]
