# Generated by Django 6.0.4 on 2026-05-26 19:41

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_formula_edging_price_cm_formula_seam_price_cm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructorGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=180, verbose_name='Название')),
                ('image', models.ImageField(upload_to=shop.models.upload_to, verbose_name='Изображение')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('draft', 'Черновик'), ('archived', 'Снят с публикации')], default='active', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Изображение конструктора',
                'verbose_name_plural': 'Изображения конструктора',
                'ordering': ('position', 'id'),
            },
        ),
    ]
