# Generated by Django 6.0.4 on 2026-05-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_form_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_gateway',
            field=models.CharField(blank=True, max_length=40, verbose_name='Платежный шлюз'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_order_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='ID платежа в шлюзе'),
        ),
    ]
