# Generated by Django 6.0.4 on 2026-05-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_payment_form_url_order_payment_gateway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image_caption',
            field=models.CharField(blank=True, default='Индивидуальные защитные чехлы для сада', max_length=180, verbose_name='Подпись на изображении'),
        ),
        migrations.AddField(
            model_name='review',
            name='location',
            field=models.CharField(blank=True, default='г. Москва', max_length=120, verbose_name='Город / метка'),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='Все понравилось!', max_length=180, verbose_name='Заголовок'),
        ),
    ]
