# Generated by Django 6.0.4 on 2026-05-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_review_image_caption_review_location_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_ready_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Оплата доступна с'),
        ),
    ]
