# Generated by Django 6.0.4 on 2026-05-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_constructorattachment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cdek_order_uuid',
            field=models.CharField(blank=True, max_length=120, verbose_name='UUID заказа СДЭК'),
        ),
        migrations.AddField(
            model_name='order',
            name='cdek_status_code',
            field=models.CharField(blank=True, max_length=80, verbose_name='Код статуса СДЭК'),
        ),
        migrations.AddField(
            model_name='order',
            name='cdek_status_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Статус СДЭК'),
        ),
        migrations.AddField(
            model_name='order',
            name='cdek_status_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата статуса СДЭК'),
        ),
        migrations.AddField(
            model_name='order',
            name='cdek_tracking_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Проверка СДЭК'),
        ),
    ]
