# Generated by Django 6.0.4 on 2026-06-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_order_cdek_order_uuid_order_cdek_status_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='bank',
            field=models.CharField(blank=True, max_length=180, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='company_legal_form',
            field=models.CharField(blank=True, max_length=40, verbose_name='Форма юр. лица'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=180, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='inn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='kpp',
            field=models.CharField(blank=True, max_length=20, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='legal_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='ogrn',
            field=models.CharField(blank=True, max_length=30, verbose_name='ОГРН / ОГРНИП'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='settlement_account',
            field=models.CharField(blank=True, max_length=40, verbose_name='Расчетный счет'),
        ),
        migrations.AddField(
            model_name='drawingorder',
            name='bank',
            field=models.CharField(blank=True, max_length=180, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='drawingorder',
            name='company_legal_form',
            field=models.CharField(blank=True, max_length=40, verbose_name='Форма юр. лица'),
        ),
        migrations.AddField(
            model_name='drawingorder',
            name='company_name',
            field=models.CharField(blank=True, max_length=180, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='drawingorder',
            name='customer_type',
            field=models.CharField(choices=[('person', 'Физическое лицо'), ('entrepreneur', 'ИП'), ('company', 'Юридическое лицо')], default='person', max_length=30, verbose_name='Тип клиента'),
        ),
        migrations.AddField(
            model_name='drawingorder',
            name='inn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='drawingorder',
            name='kpp',
            field=models.CharField(blank=True, max_length=20, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='drawingorder',
            name='legal_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='drawingorder',
            name='ogrn',
            field=models.CharField(blank=True, max_length=30, verbose_name='ОГРН / ОГРНИП'),
        ),
        migrations.AddField(
            model_name='drawingorder',
            name='settlement_account',
            field=models.CharField(blank=True, max_length=40, verbose_name='Расчетный счет'),
        ),
    ]
