# Generated by Django 6.0.4 on 2026-06-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_customerprofile_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bank',
            field=models.CharField(blank=True, max_length=180, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='order',
            name='company_legal_form',
            field=models.CharField(blank=True, max_length=40, verbose_name='Форма юр. лица'),
        ),
        migrations.AddField(
            model_name='order',
            name='company_name',
            field=models.CharField(blank=True, max_length=180, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='order',
            name='inn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='order',
            name='kpp',
            field=models.CharField(blank=True, max_length=20, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='order',
            name='legal_address',
            field=models.TextField(blank=True, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='order',
            name='ogrn',
            field=models.CharField(blank=True, max_length=30, verbose_name='ОГРН / ОГРНИП'),
        ),
        migrations.AddField(
            model_name='order',
            name='settlement_account',
            field=models.CharField(blank=True, max_length=40, verbose_name='Расчетный счет'),
        ),
    ]
