# Generated by Django 6.0.4 on 2026-06-03 15:10

import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_order_bank_order_company_legal_form_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructorGalleryExtraImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(upload_to=shop.models.upload_to, verbose_name='Изображение')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('constructor_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.constructorgalleryimage', verbose_name='Изображение конструктора')),
            ],
            options={
                'verbose_name': 'Дополнительное изображение конструктора',
                'verbose_name_plural': 'Дополнительные изображения конструктора',
                'ordering': ('position', 'id'),
            },
        ),
    ]
